### ISSUE TITLE
Remove Instagram

### ISSUE THREAD

**Issue by BrettonDoesNails** [Taouen/bretton-does-nails#3]
I dont like that i have to post instagram on there manually. Can we just ditch it. It’s too much work

**Comment by Taouen** [comment]
I can remove it, but then the page needs something else. Probably needs more as is, it's a pretty sparsely populated page.

**Comment by BrettonDoesNails** [comment]
Can all the old news just go there? 

Bretton Does Nails
(And other things, too!)
@bretton.does.nails

**Comment by Taouen** [comment]
Moving to email, this isn't really so much an issue as a discussion.
